------------------------------------------------------------------------------------
--                                  Angel's mods                                  --
------------------------------------------------------------------------------------
if not BioInd.check_mods({
  "angelspetrochem",
  "angelsbioprocessing",
  "angelsrefining",
}) then
  BioInd.nothing_to_do("*")
  -- require("file") will return true unless the file returns a value ~= nil
  return {}
else
  BioInd.entered_file()
  BioInd.writeDebug("Reading patterns for Angel's mods")
end


------------------------------------------------------------------------------------
------------------------------------------------------------------------------------


-- Dictionary of item.name and item.type
local blacklist_items = {
  --~ ["alien-bacteria"]            = "item",
  --~ ["angels-electric-boiler"]    = "item",
  --~ ["angels-flare-stack"]        = "item",
  --~ ["angels-quartz-crucible"]    = "item",
  --~ ["bio-butchery"]              = "item",
  --~ ["bio-hatchery"]              = "item",
  --~ ["bio-plastic"]               = "item",
  --~ ["bio-press"]                 = "item",
  --~ ["bio-processor"]             = "item",
  --~ ["bio-raw-meat"]              = "item",
  --~ ["bio-resin"]                 = "item",
  --~ ["bio-rubber"]                = "item",
  --~ ["chemical-void"]             = "item",
  --~ ["filter-ceramic"]            = "item",
  --~ ["filter-coal"]               = "item",
  --~ ["filter-frame"]              = "item",
  --~ ["petri-dish"]                = "item",
  --~ ["reinforced-concrete-brick"] = "item",
  --~ ["solid-alginic-acid"]        = "item",
  --~ ["solid-beans"]               = "item",
  --~ ["solid-compost"]             = "item",
  --~ ["solid-corn"]                = "item",
  --~ ["solid-flour"]               = "item",
  --~ ["solid-fruit"]               = "item",
  --~ ["solid-mud"]                 = "item",
  --~ ["solid-nuts"]                = "item",
  --~ ["solid-oil-residual"]        = "item",
  --~ ["solid-pips"]                = "item",
  --~ ["solid-resin"]               = "item",
  --~ ["solid-rubber"]              = "item",
  --~ ["solid-salt"]                = "item",
  --~ ["solid-sand"]                = "item",
  --~ ["solid-saw"]                 = "item",
  --~ ["solid-soil"]                = "item",
  --~ ["solid-tree"]                = "item",
  --~ ["solid-tungsten-oxide"]      = "item",
  --~ ["substrate-dish"]            = "item",

  --~ ["electronic-circuit"]        = "item",
  ["alien-bacteria"]            = "item",
  ["angels-electric-boiler"]    = "item",
  ["angels-flare-stack"]        = "item",
  ["angels-quartz-crucible"]    = "item",
  ["bio-butchery"]              = "item",
  ["bio-hatchery"]              = "item",
  ["bio-plastic"]               = "item",
  ["bio-press"]                 = "item",
  ["bio-processor"]             = "item",
  ["bio-raw-meat"]              = "item",
  ["bio-resin"]                 = "item",
  ["bio-rubber"]                = "item",
  ["chemical-void"]             = "item",
  ["filter-ceramic"]            = "item",
  ["filter-coal"]               = "item",
  ["filter-frame"]              = "item",
  ["petri-dish"]                = "item",
  ["reinforced-concrete-brick"] = "item",
  ["solid-alginic-acid"]        = "item",
  ["solid-beans"]               = "item",
  ["solid-compost"]             = "item",
  ["solid-corn"]                = "item",
  ["solid-flour"]               = "item",
  ["solid-fruit"]               = "item",
  ["solid-mud"]                 = "item",
  ["solid-nuts"]                = "item",
  ["solid-oil-residual"]        = "item",
  ["solid-pips"]                = "item",
  ["solid-resin"]               = "item",
  ["solid-rubber"]              = "item",
  ["solid-salt"]                = "item",
  ["solid-sand"]                = "item",
  ["solid-saw"]                 = "item",
  ["solid-soil"]                = "item",
  ["solid-tree"]                = "item",
  ["solid-tungsten-oxide"]      = "item",
  ["substrate-dish"]            = "item",

  ["electronic-circuit"]        = "item",
}

local blacklist_patterns = {
-- Bio stuff
  ".*fish.*",
  ".*seed.*",
  "^algae%-.+",
  "^bio%-hogger%-%d",
  "^bio%-puffer%-.+",
  "^bio%-refugium%-.+",
  "^biter%-.+",
  "^desert%-.+",
  "^sponge%-.+",
  "^swamp%-.+",
  "^temperate%-.+",
  --~ "^tree.*%-seed",

-- Production
  ".*nuclear.*",
  "^angels%-electrode.*",
  "^angels%-electrolyser.*",
  "^angels%-ore%d.*",
  "^angels%-rod%-.+",
  "^angels%-solder.*",
  "^bio-arboretum%-.+",
  "^anode%-.+",
  "^casting%-machine.*",
  "^catalysator%-.+",
  "^catalyst%-.+",
  "^cathode%-.+",
  "^crystallizer.*",
  "^filter%-.+%-used",
  "^geode%-.+",
  "^milling%-drum.*",
  "^separator.*",
  "^sintering%-.+",
  "^steam%-.+",
  "^strand%-casting.+",

-- Resources
  "^aluminium%-.+",
  ".+%-aluminium%-.+",
  ".+%-aluminium$",
  "^ammonium%-.+",
  ".+%-ammonium%-.+",
  ".+%-ammonium$",
  "^calcium%-.+",
  ".+%-calcium%-.+",
  ".+%-calcium$",
  "^cement%-.+",
  ".+%-cement%-.+",
  ".+%-cement$",
  "^chrom%-.+",
  ".+%-chrom%-.+",
  ".+%-chrom$",
  "^clay%-.+",
  ".+%-clay%-.+",
  ".+%-clay$",
  "^cobalt%-.+",
  ".+%-cobalt%-.+",
  ".+%-cobalt$",
  "^crystal%-.+",
  ".+%-crystal%-.+",
  ".+%-crystal$",
  "^glass%-.+",
  ".+%-glass%-.+",
  ".+%-glass$",
  "^gold%-.+",
  ".+%-gold%-.+",
  ".+%-gold$",
  "^lead%-.+",
  ".+%-lead%-.+",
  ".+%-lead$",
  "^lime%-.+",
  ".+%-lime%-.+",
  ".+%-lime$",
  "^lithium%-.+",
  ".+%-lithium%-.+",
  ".+%-lithium$",
  "^manganese%-.+",
  ".+%-manganese%-.+",
  ".+%-manganese$",
  "^nickel%-.+",
  ".+%-nickel%-.+",
  ".+%-nickel$",
  "^platinum%-.+",
  ".+%-platinum%-.+",
  ".+%-platinum$",
  "^quartz%-.+",
  ".+%-quartz%-.+",
  ".+%-quartz$",
  "^silica%-.+",
  ".+%-silica%-.+",
  ".+%-silica$",
  "^silicon%-.+",
  ".+%-silicon%-.+",
  ".+%-silicon$",
  "^silver%-.+",
  ".+%-silver%-.+",
  ".+%-silver$",
  "^slag%-.+",
  ".+%-slag%-.+",
  ".+%-slag$",
  "^solder%-.+",
  ".+%-solder%-.+",
  ".+%-solder$",
  "^steel%-.+",
  ".+%-steel%-.+",
  ".+%-steel$",
  "^tin%-.+",
  ".+%-tin%-.+",
  ".+%-tin$",
  "^titanium%-.+",
  ".+%-titanium%-.+",
  ".+%-titanium$",
  "^tungsten%-.+",
  ".+%-tungsten%-.+",
  ".+%-tungsten$",
  "^zinc%-.+",
  ".+%-zinc%-.+",
  ".+%-zinc$",
  "^solid%-.+oxide",
  "^solid%-sodium.*",
}

local whitelist_items = {}

local whitelist_patterns = {}

------------------------------------------------------------------------------------
--                                    END OF FILE
------------------------------------------------------------------------------------
BioInd.entered_file("leave")

return {
  blacklist_items = blacklist_items or {},
  whitelist_items = whitelist_items or {},
  blacklist_patterns = blacklist_patterns or {},
  whitelist_patterns = whitelist_patterns or {},
}
