--~ ------------------------------------------------------------------------------------
--~ --                                  Alien biomes                                  --
--~ ------------------------------------------------------------------------------------
--~ local mod_name = "alien-biomes"
--~ if not BI.check_mods(mod_name) then
  --~ BI.nothing_to_do("*")
  --~ return
--~ else
  --~ BI.entered_file()
--~ end

--~ local BioInd = require('common')('Bio_Industries')

--~ local ICONPATH = BioInd.iconpath

------------------------------------------------------------------------------------
------------------------------------------------------------------------------------

-- Moved to data-final-fixes!

--~ --- Make it so that the Base game tile "grass" can't be placed in blueprints
--~ --- New as of 0.16
--~ BioInd.writeDebug("Removing grass tiles from blueprints")
--~ for _, tile in ipairs{"grass-1", "grass-2", "grass-3", "grass-4"} do
  --~ BI_Functions.lib.remove_from_blueprint(tile)
--~ end

--~ BioInd.writeDebug("Removing AB tiles from blueprints")
--~ local patterns = {
  --~ "frozen%-snow%-%d",
  --~ "mineral%-aubergine%-dirt%-%d",
  --~ "mineral%-aubergine%-sand%-%d",
  --~ "mineral%-beige%-dirt%-%d",
  --~ "mineral%-beige%-sand%-%d",
  --~ "mineral%-black%-dirt%-%d",
  --~ "mineral%-black%-sand%-%d",
  --~ "mineral%-brown%-dirt%-%d",
  --~ "mineral%-brown%-sand%-%d",
  --~ "mineral%-cream%-dirt%-%d",
  --~ "mineral%-cream%-sand%-%d",
  --~ "mineral%-dustyrose%-dirt%-%d",
  --~ "mineral%-dustyrose%-sand%-%d",
  --~ "mineral%-grey%-dirt%-%d",
  --~ "mineral%-grey%-sand%-%d",
  --~ "mineral%-purple%-dirt%-%d",
  --~ "mineral%-purple%-sand%-%d",
  --~ "mineral%-red%-dirt%-%d",
  --~ "mineral%-red%-sand%-%d",
  --~ "mineral%-tan%-dirt%-%d",
  --~ "mineral%-tan%-sand%-%d",
  --~ "mineral%-violet%-dirt%-%d",
  --~ "mineral%-violet%-sand%-%d",
  --~ "mineral%-white%-dirt%-%d",
  --~ "mineral%-white%-sand%-%d",
  --~ "vegetation%-blue%-grass%-%d",
  --~ "vegetation%-green%-grass%-%d",
  --~ "vegetation%-mauve%-grass%-%d",
  --~ "vegetation%-olive%-grass%-%d",
  --~ "vegetation%-orange%-grass%-%d",
  --~ "vegetation%-purple%-grass%-%d",
  --~ "vegetation%-red%-grass%-%d",
  --~ "vegetation%-turquoise%-grass%-%d",
  --~ "vegetation%-violet%-grass%-%d",
  --~ "vegetation%-yellow%-grass%-%d",
  --~ "volcanic%-blue%-heat%-%d",
  --~ "volcanic%-green%-heat%-%d",
  --~ "volcanic%-orange%-heat%-%d",
  --~ "volcanic%-purple%-heat%-%d",
--~ }
--~ for tile_name, tile in pairs(data.raw.tile) do
  --~ for p, pattern in ipairs(patterns) do
    --~ if tile_name:match(pattern) then
      --~ BI_Functions.lib.remove_from_blueprint(tile)
      --~ break
    --~ end
  --~ end
--~ end


--~ ------------------------------------------------------------------------------------
--~ --                                    END OF FILE
--~ ------------------------------------------------------------------------------------
--~ BI.entered_file("leave")
